"""Format PR analysis results as GitHub-flavored markdown."""

from __future__ import annotations

from sentinel.core.pr_analyzer import PRAnalysis


def format_pr_comment(analysis: PRAnalysis) -> str:
    """Format a PRAnalysis as a GitHub PR comment in markdown."""
    parts: list[str] = []

    # Summary
    finding_count = len(analysis.findings)
    hot_count = len(analysis.hot_files_touched)
    risk = "HIGH" if hot_count > 0 or finding_count > 3 else "LOW" if finding_count == 0 else "MEDIUM"

    parts.append("## Sentinel PR Review\n")
    parts.append(
        f"**{len(analysis.changed_files)} files changed** | "
        f"**{finding_count} findings** | "
        f"**Risk: {risk}**\n"
    )

    # Risk Assessment — hot files
    if analysis.hot_files_touched:
        parts.append("### Risk Assessment\n")
        parts.append("| Hot File | Churn | Changes | Bug Fixes |")
        parts.append("|----------|-------|---------|-----------|")
        for hf in analysis.hot_files_touched:
            parts.append(
                f"| `{hf.file_path}` | {hf.churn_score:.0f} | "
                f"{hf.change_count} | {hf.bug_fix_count} |"
            )
        parts.append("")

    # Findings
    if analysis.findings:
        parts.append("### Findings\n")
        for f in analysis.findings:
            sev = f.severity.value.upper()
            line_str = f" (line {f.line})" if f.line else ""
            parts.append(f"- **[{sev}]** `{f.file_path}`{line_str}: {f.message}")
            if f.suggestion:
                parts.append(f"  - *Suggestion:* {f.suggestion}")
        parts.append("")

    # Co-change reminders
    if analysis.missing_co_changes:
        parts.append("### Co-Change Reminders\n")
        parts.append("These files usually change together but weren't in this PR:\n")
        for changed, missing, count in analysis.missing_co_changes:
            parts.append(f"- `{changed}` usually changes with `{missing}` ({count} co-changes)")
        parts.append("")

    # Relevant context
    if analysis.relevant_decisions or analysis.relevant_pitfalls:
        parts.append("### Relevant Context\n")
        if analysis.relevant_decisions:
            parts.append("**Decisions:**")
            for d in analysis.relevant_decisions[:5]:
                parts.append(f"- {d.summary}")
            parts.append("")
        if analysis.relevant_pitfalls:
            parts.append("**Pitfalls:**")
            for p in analysis.relevant_pitfalls[:5]:
                parts.append(f"- **[{p.severity.value}]** {p.description}")
            parts.append("")

    # Footer
    parts.append("---")
    parts.append(
        "*Generated by [Sentinel](https://github.com/evo-nirvana/sentinel) "
        "| Submit feedback with `sentinel feedback submit <id> accepted|rejected`*"
    )

    return "\n".join(parts)
